@echo off
echo Creating virtual environment...
python -m venv venv
echo Activating virtual environment...
call venv\Scripts\activate.bat
echo Installing dependencies...
pip install -r requirements.txt
echo Setup complete! Virtual environment is ready.
echo To activate in the future, run: venv\Scripts\activate.bat